### ISSUE TITLE
Broken link in mne-scripts/brainstorm/run_freesurfer_recon.sh

### ISSUE THREAD

**Issue by ftadel** [mne-tools/mne-scripts#17]
I received a some complaints from the google search console that the link http://neuroimage.usc.edu/bst/getupdate.php?u=mne was not working on my server. 
Indeed, this file doesn't exist, it disappeared a while ago...
We don't use this dataset, if you need it, maybe upload it somewhere else.

**Comment by agramfort** [comment]
we don't need it. We should just remove it from run_freesurfer_recon.sh

**Comment by agramfort** [comment]
it's not a bug actually as  the link that the script uses is:

http://neuroimage.usc.edu/bst/getupdate.php?u=mne\&s=sample_auditory

which exists. It's a bug of the web crawler.
